variables:
  DOCKER_DRIVER: overlay
  MAVEN_CLI_OPTS: "-s /data/.m2/settings.xml"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  APP_DOCKERFILE_LOCATION: "Dockerfile"
  APP_IMAGE_NAME: "romeway"

default:
  tags:
    - nexclipper
  services:
    - docker:dind
  image: docker:latest
  retry: 2

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository

stages:
  - build
  - package
  - deploy-escargot

maven-build:
  image: maven:3.8.4-jdk-11
  stage: build
  script:
    - mvn clean package -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/*.jar
  only:
    - /\b^(issue|feature|bugfix|improvement).*$\b/
    - $CI_DEFAULT_BRANCH

docker-build:
  stage: package
  before_script:
    - "apk add --no-cache git"
  script:
    - "source /data/scripts/build.sh $APP_IMAGE_NAME"
  only:
    - /\b^(issue|feature|bugfix|improvement).*$\b/
    - $CI_DEFAULT_BRANCH

deploy-romeway:
  stage: deploy-escargot
  image: dtzar/helm-kubectl:latest
  before_script:
    - echo "Setup Open VPN"
    - which openvpn || (apk update  -qq && apk add -qq openvpn && apk add  -qq iputils)
    - cat $CLIENT_OVPN > /etc/openvpn/client.ovpn
    - cat <<< $VPN_USER > /etc/openvpn/cred.txt
    - cat <<< $VPN_PASS >> /etc/openvpn/cred.txt # append at the bottom
    - openvpn --config /etc/openvpn/client.ovpn --auth-user-pass /etc/openvpn/cred.txt --daemon
    - sleep 15
    - echo "nameserver 8.8.8.8" >> /etc/resolv.conf
    - ping -c3 lib.nexclipper.io
    - echo -e "\nLogin to Kubernetes"
    - source /data/scripts/login-cluster-seoul.sh escargot
  script:
    - "source /data/scripts/deploy.sh nc"
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always
    - if: $CI_COMMIT_BRANCH =~ /\b^(issue|feature|bugfix|improvement).*$\b/
      when: manual

  